"""initial schema

Creates every table the platform starts from, then converts `bars` into a
TimescaleDB hypertable. The conversion belongs here rather than in
`infra/db/init/` because the table has to exist before it can be partitioned,
and keeping the schema in migrations means one source of truth for it. The
extension itself is still the database's business, not the schema's — see
`_require_timescale` below.

Revision ID: 8140ae9c6209
Revises:
Create Date: 2026-08-15 02:39:20.113367

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "8140ae9c6209"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 7-day chunks suit minute bars; 30 days is the better fit if only dailies are
#: ever stored. Compression after 30 days typically gives 10-20x on OHLCV, and
#: old bars are read constantly by backtests but never updated.
CHUNK_INTERVAL = "7 days"
COMPRESS_AFTER = "30 days"

_TIMESCALE_MISSING = (
    "The timescaledb extension is not installed in this database, so `bars` "
    "cannot be made a hypertable.\n\n"
    "This migration refuses to fall back to a plain table. `bars` is the only "
    "table here that grows without bound, and an unpartitioned, uncompressed "
    "version of it works fine for weeks before becoming the platform's "
    "bottleneck — by which point converting it means downtime on the largest "
    "table you have.\n\n"
    "Use the timescale/timescaledb image (see docker-compose.yml), which runs "
    "infra/db/init/01-timescaledb.sql on first start, or create the extension "
    "yourself with: CREATE EXTENSION IF NOT EXISTS timescaledb;"
)


def _timescale_installed() -> bool:
    bind = op.get_bind()
    return (
        bind.execute(sa.text("SELECT 1 FROM pg_extension WHERE extname = 'timescaledb'")).scalar()
        is not None
    )


def _require_timescale() -> None:
    """Fail loudly rather than silently degrade to a plain table."""
    if not _timescale_installed():
        raise RuntimeError(_TIMESCALE_MISSING)


def upgrade() -> None:
    # Checked before any DDL runs, so a database without the extension fails
    # with the message above rather than half a schema.
    _require_timescale()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_ts"), "audit_log", ["ts"], unique=False)
    op.create_table(
        "bars",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("vwap", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("trade_count", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "ts"),
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_exposure", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("run_mode", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equity_snapshots_ts"), "equity_snapshots", ["ts"], unique=False)
    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("avg_entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("last_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("run_mode", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_possnap_ts_symbol", "position_snapshots", ["ts", "symbol"], unique=False)
    op.create_table(
        "strategies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("class_name", sa.String(length=100), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("ruleset", sa.JSON(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("universe", sa.JSON(), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("risk_config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("equity_curve", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("strategy_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strength", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("indicators", sa.JSON(), nullable=False),
        sa.Column("acted_on", sa.Boolean(), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_signals_strategy_ts", "signals", ["strategy_id", "ts"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("client_order_id", sa.String(length=128), nullable=False),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("strategy_id", sa.String(length=36), nullable=True),
        sa.Column("signal_id", sa.String(length=36), nullable=True),
        sa.Column("parent_order_id", sa.String(length=36), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("time_in_force", sa.String(length=8), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("filled_qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("avg_fill_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("run_mode", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_order_id", name="uq_orders_client_order_id"),
    )
    op.create_index(op.f("ix_orders_broker_order_id"), "orders", ["broker_order_id"], unique=False)
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_index("ix_orders_symbol_created", "orders", ["symbol", "created_at"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("venue_fill_id", sa.String(length=64), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qty", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_fill_id"),
    )
    # ### end Alembic commands ###

    # `bars` becomes a hypertable only now that it exists and is still empty:
    # converting a populated table means rewriting it. Timescale requires every
    # unique index to contain the partitioning column, which the natural key
    # (symbol, timeframe, ts) already does — that is why `ts` is in the primary
    # key rather than the table carrying a surrogate id.
    #
    # `create_default_indexes` is off. Left on, Timescale builds `bars_ts_idx` on
    # (ts DESC) — a third btree on the largest table, maintained per chunk. It
    # buys very little here: chunk exclusion already prunes by time from the
    # partitioning metadata rather than from an index, so a time-ranged scan
    # reads only the chunks it needs either way, and every query the platform
    # actually issues is scoped to a symbol and served by the primary key.
    #
    # It also cannot be left on without lying about the schema. Timescale creates
    # that index behind Alembic's back, `models.py` has no matching declaration,
    # and so `alembic check` reports drift on a clean database forever — which
    # would make the drift check useless exactly when it is needed.
    op.execute(
        sa.text(
            "SELECT create_hypertable("
            "  'bars', 'ts',"
            f"  chunk_time_interval => INTERVAL '{CHUNK_INTERVAL}',"
            "  create_default_indexes => FALSE,"
            "  if_not_exists => TRUE"
            ")"
        )
    )

    # Segment by the columns every query filters on, so a compressed chunk can
    # still be read for one symbol without decompressing its neighbours.
    op.execute(
        sa.text(
            "ALTER TABLE bars SET ("
            "  timescaledb.compress,"
            "  timescaledb.compress_segmentby = 'symbol, timeframe'"
            ")"
        )
    )
    op.execute(sa.text(f"SELECT add_compression_policy('bars', INTERVAL '{COMPRESS_AFTER}')"))


def downgrade() -> None:
    # The policy is a background job that outlives a plain DROP TABLE, so it
    # goes first. Guarded because a database that never had the extension never
    # got this far in `upgrade`.
    if _timescale_installed():
        op.execute(sa.text("SELECT remove_compression_policy('bars', if_exists => TRUE)"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fills")
    op.drop_index("ix_orders_symbol_created", table_name="orders")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_broker_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_signals_strategy_ts", table_name="signals")
    op.drop_table("signals")
    op.drop_table("backtest_runs")
    op.drop_table("strategies")
    op.drop_index("ix_possnap_ts_symbol", table_name="position_snapshots")
    op.drop_table("position_snapshots")
    op.drop_index(op.f("ix_equity_snapshots_ts"), table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    op.drop_table("bars")
    op.drop_index(op.f("ix_audit_log_ts"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
