"""Orders and fills.

An `Order` is mutable state machine data, not a value object: it accumulates
fills over its life. Legal transitions live in `atp_core.execution.state`.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from typing import TYPE_CHECKING

from atp_core.domain.enums import OrderStatus, OrderType, Side, TimeInForce

if TYPE_CHECKING:
    from datetime import datetime


@dataclass(frozen=True, slots=True)
class Fill:
    """One execution against an order. Orders fill in pieces (CLAUDE.md §5)."""

    order_id: str
    ts: datetime
    qty: Decimal
    price: Decimal
    fee: Decimal = Decimal(0)
    venue_fill_id: str | None = None

    @property
    def notional(self) -> Decimal:
        return self.qty * self.price


@dataclass(slots=True)
class Order:
    """An instruction to the market.

    `client_order_id` is generated by us before submission and reused on every
    retry (rule §1.4). It is the idempotency key: if a submit times out, we
    query by this id rather than resubmitting blind and risking a double
    position. `broker_order_id` is assigned by the venue on acknowledgement.
    """

    symbol: str
    side: Side
    qty: Decimal
    order_type: OrderType = OrderType.MARKET
    time_in_force: TimeInForce = TimeInForce.DAY
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    trail_percent: Decimal | None = None

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    client_order_id: str = field(default_factory=lambda: f"atp-{uuid.uuid4().hex[:20]}")
    broker_order_id: str | None = None

    strategy_id: str | None = None
    signal_id: str | None = None
    parent_order_id: str | None = None  # set on protective stop/target children

    status: OrderStatus = OrderStatus.PENDING_RISK
    filled_qty: Decimal = Decimal(0)
    avg_fill_price: Decimal | None = None
    fills: list[Fill] = field(default_factory=list)

    created_at: datetime | None = None
    submitted_at: datetime | None = None
    filled_at: datetime | None = None
    reject_reason: str | None = None

    def __post_init__(self) -> None:
        if self.qty <= 0:
            raise ValueError(f"order qty must be positive (side carries direction), got {self.qty}")
        if self.order_type in (OrderType.LIMIT, OrderType.STOP_LIMIT) and self.limit_price is None:
            raise ValueError(f"{self.order_type} requires limit_price")
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT) and self.stop_price is None:
            raise ValueError(f"{self.order_type} requires stop_price")

    @property
    def remaining_qty(self) -> Decimal:
        return self.qty - self.filled_qty

    @property
    def is_complete(self) -> bool:
        return self.status.is_terminal

    @property
    def signed_filled_qty(self) -> Decimal:
        """Filled quantity as a position delta: negative for sells."""
        return self.filled_qty * self.side.sign

    def apply_fill(self, fill: Fill) -> None:
        """Record an execution, updating the volume-weighted average price.

        Recomputing VWAP incrementally (rather than storing the last price)
        is what makes P&L correct for orders that fill across many prints.
        """
        if fill.qty <= 0:
            raise ValueError(f"fill qty must be positive, got {fill.qty}")
        if fill.qty > self.remaining_qty:
            raise ValueError(
                f"overfill on {self.id}: fill {fill.qty} > remaining {self.remaining_qty}"
            )

        prior_notional = (self.avg_fill_price or Decimal(0)) * self.filled_qty
        self.filled_qty += fill.qty
        self.avg_fill_price = (prior_notional + fill.notional) / self.filled_qty
        self.fills.append(fill)

        if self.remaining_qty == 0:
            self.status = OrderStatus.FILLED
            self.filled_at = fill.ts
        else:
            self.status = OrderStatus.PARTIALLY_FILLED

    @property
    def total_fees(self) -> Decimal:
        return sum((f.fee for f in self.fills), Decimal(0))


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """What a strategy asks for, before sizing and risk approval.

    Kept separate from `Order` so that a strategy cannot construct something the
    risk engine has not seen — there is exactly one path from request to order
    (rule §1.5).
    """

    symbol: str
    side: Side
    order_type: OrderType = OrderType.MARKET
    qty: Decimal | None = None  # None → let the position sizer decide
    notional: Decimal | None = None
    limit_price: Decimal | None = None
    stop_loss_price: Decimal | None = None
    take_profit_price: Decimal | None = None
    time_in_force: TimeInForce = TimeInForce.DAY
    strategy_id: str | None = None
    signal_id: str | None = None
