"""Orders and fills.

An `Order` is mutable state machine data, not a value object: it accumulates
fills over its life. Legal transitions live in `atp_core.execution.state`.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from typing import TYPE_CHECKING

from atp_core.domain.enums import OrderStatus, OrderType, Side, TimeInForce

if TYPE_CHECKING:
    from datetime import datetime


@dataclass(frozen=True, slots=True)
class Fill:
    """One execution against an order. Orders fill in pieces (CLAUDE.md §5)."""

    order_id: str
    ts: datetime
    qty: Decimal
    price: Decimal
    fee: Decimal = Decimal(0)
    venue_fill_id: str | None = None

    @property
    def notional(self) -> Decimal:
        return self.qty * self.price


@dataclass(slots=True)
class Order:
    """An instruction to the market.

    `client_order_id` is generated by us before submission and reused on every
    retry (rule §1.4). It is the idempotency key: if a submit times out, we
    query by this id rather than resubmitting blind and risking a double
    position. `broker_order_id` is assigned by the venue on acknowledgement.

    The default factory below is random, which makes it unique but **not**
    reproducible: rebuild this order from a persisted request or after a restart
    and it mints a different key. It is a fallback for an order nobody is going
    to retry (a fixture, a backtest fill that never leaves the process). Every
    order that reaches a venue gets its key from
    `atp_core.execution.idempotency.client_order_id`, derived from the decision
    rather than from the object — that derivation, not this default, is what
    rule §1.4 promises.
    """

    symbol: str
    side: Side
    qty: Decimal
    order_type: OrderType = OrderType.MARKET
    time_in_force: TimeInForce = TimeInForce.DAY
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    trail_percent: Decimal | None = None

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    client_order_id: str = field(default_factory=lambda: f"atp-{uuid.uuid4().hex[:20]}")
    broker_order_id: str | None = None

    strategy_id: str | None = None
    signal_id: str | None = None
    parent_order_id: str | None = None  # set on protective stop/target children

    #: What this order is for, carried over from the `OrderRequest` that built
    #: it. Already part of the identity — `client_order_id` is derived from it —
    #: but it lived only inside that derivation, which made it unrecoverable
    #: from a stored order: a hash cannot be read backwards. It is here because
    #: it is the only thing that can say *why* a position closed, and
    #: `analytics.performance` groups P&L by exactly that (a strategy whose
    #: profits come from targets while its stops bleed has a stop-placement
    #: problem, not a signal problem). The vocabulary lives in
    #: `atp_core.execution.idempotency`; the default is the bare string because
    #: `domain/` imports nothing from its siblings.
    purpose: str = "entry"

    status: OrderStatus = OrderStatus.PENDING_RISK
    filled_qty: Decimal = Decimal(0)
    avg_fill_price: Decimal | None = None
    fills: list[Fill] = field(default_factory=list)

    created_at: datetime | None = None
    submitted_at: datetime | None = None
    filled_at: datetime | None = None
    reject_reason: str | None = None

    def __post_init__(self) -> None:
        if self.qty <= 0:
            raise ValueError(f"order qty must be positive (side carries direction), got {self.qty}")
        if self.order_type in (OrderType.LIMIT, OrderType.STOP_LIMIT) and self.limit_price is None:
            raise ValueError(f"{self.order_type} requires limit_price")
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT) and self.stop_price is None:
            raise ValueError(f"{self.order_type} requires stop_price")
        if not self.purpose:
            # Same refusal `OrderRequest` makes, for the same reason: an empty
            # purpose is an order whose identity cannot be derived, and an exit
            # nothing can attribute.
            raise ValueError("an order needs a purpose — it is part of its identity")

    @property
    def remaining_qty(self) -> Decimal:
        return self.qty - self.filled_qty

    @property
    def is_complete(self) -> bool:
        return self.status.is_terminal

    @property
    def signed_filled_qty(self) -> Decimal:
        """Filled quantity as a position delta: negative for sells."""
        return self.filled_qty * self.side.sign

    def apply_fill(self, fill: Fill) -> None:
        """Record an execution, updating the volume-weighted average price.

        Recomputing VWAP incrementally (rather than storing the last price)
        is what makes P&L correct for orders that fill across many prints.
        """
        if fill.qty <= 0:
            raise ValueError(f"fill qty must be positive, got {fill.qty}")
        if fill.qty > self.remaining_qty:
            raise ValueError(
                f"overfill on {self.id}: fill {fill.qty} > remaining {self.remaining_qty}"
            )

        prior_notional = (self.avg_fill_price or Decimal(0)) * self.filled_qty
        self.filled_qty += fill.qty
        self.avg_fill_price = (prior_notional + fill.notional) / self.filled_qty
        self.fills.append(fill)

        if self.remaining_qty == 0:
            self.status = OrderStatus.FILLED
            self.filled_at = fill.ts
        else:
            self.status = OrderStatus.PARTIALLY_FILLED

    @property
    def total_fees(self) -> Decimal:
        return sum((f.fee for f in self.fills), Decimal(0))


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """What a strategy asks for, before sizing and risk approval.

    Kept separate from `Order` so that a strategy cannot construct something the
    risk engine has not seen — there is exactly one path from request to order
    (rule §1.5).

    `decided_at` is the instant the decision behind this request was made: a
    signal's `ts`, the bar that triggered it, the moment a human clicked submit.
    It is required, and it is on the *request* rather than being stamped at
    submission time, because it is what makes `client_order_id` reproducible
    (rule §1.4). A request persisted to a table and replayed after a restart has
    to derive the same key it did the first time, and it can only do that if the
    instant travelled with it.

    `purpose` says what this request is for, and travels with it for the same
    reason. It is what separates two orders that agree on everything else: a
    strategy exiting a long and the same strategy opening a short on one bar are
    both a SELL, for one symbol, at one instant. The vocabulary lives in
    `atp_core.execution.idempotency`; the default here is the bare string
    because `domain/` imports nothing from its siblings.
    """

    symbol: str
    side: Side
    decided_at: datetime
    order_type: OrderType = OrderType.MARKET
    qty: Decimal | None = None  # None → let the position sizer decide
    notional: Decimal | None = None
    limit_price: Decimal | None = None
    stop_loss_price: Decimal | None = None
    take_profit_price: Decimal | None = None
    time_in_force: TimeInForce = TimeInForce.DAY
    strategy_id: str | None = None
    signal_id: str | None = None
    purpose: str = "entry"

    def __post_init__(self) -> None:
        # The domain boundary rejects naive datetimes (rule §1.2) rather than
        # letting one reach the id derivation, where it would only surface as
        # two keys for what was meant to be one order.
        if self.decided_at.tzinfo is None:
            raise ValueError(f"decided_at must be tz-aware UTC, got {self.decided_at!r}")
        if not self.purpose:
            raise ValueError("an order request needs a purpose — it is part of its identity")
        if self.qty is not None and self.notional is not None:
            raise ValueError(
                f"an order request states a quantity or a notional, not both — "
                f"got qty={self.qty} and notional={self.notional}"
            )
        if self.qty is not None and self.qty <= 0:
            raise ValueError(
                f"request qty must be positive (side carries direction), got {self.qty}"
            )
        if self.notional is not None and self.notional <= 0:
            raise ValueError(f"request notional must be positive, got {self.notional}")
