/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analytics/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attribution
         * @description P&L grouped by strategy | symbol | weekday | hour | exit_reason.
         */
        get: operations["get_attribution_api_v1_analytics_attribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/live-vs-backtest/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Vs Backtest
         * @description Is live performing as the backtest promised?
         *
         *     The most important report here. Persistent negative divergence means the
         *     backtest was wrong — overfitting, unmodelled costs, or unachievable fills.
         */
        get: operations["live_vs_backtest_api_v1_analytics_live_vs_backtest__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Performance
         * @description Full metric set over a period.
         */
        get: operations["get_performance_api_v1_analytics_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/reports/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily Report
         * @description End-of-day summary: P&L, trades, rejections, halts, feed incidents.
         */
        get: operations["daily_report_api_v1_analytics_reports_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trades
         * @description Completed round trips with MAE/MFE.
         */
        get: operations["list_trades_api_v1_analytics_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Context
         * @description The run mode, before there is a session.
         *
         *     docs/DASHBOARD.md calls the run-mode banner the most important pixel on the
         *     screen, and the moment before signing in is not an exception — it is when
         *     the operator is still deciding whether to open a live-money system. So the
         *     login screen needs this one fact, and needs it unauthenticated.
         *
         *     It cannot come from the root `/` handler, which returns the same thing: in
         *     the deployed arrangement nginx serves the dashboard at `/`, so a request
         *     there gets `index.html` and never reaches the API at all. That is not a
         *     proxy misconfiguration — `/` is where the SPA belongs — it just means
         *     anything the browser needs must live under `/api`. This was found by
         *     signing in through the real proxy, having passed a unit test whose stub
         *     matched the path too loosely.
         *
         *     Deliberately nothing else. Run mode discloses whether real money is at
         *     stake, which is a warning rather than a secret; the book, the account and
         *     the halts all stay behind the session.
         */
        get: operations["context_api_v1_auth_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange a username and password for a session cookie.
         *
         *     There is no rate limit here yet — that is its own Phase 6 item. What stands
         *     in for one meanwhile is bcrypt itself: a cost-12 hash takes roughly a
         *     quarter-second to verify, which is a poor rate for guessing and is why the
         *     work factor is not tuned down. It is a brake, not a lock, and the item above
         *     it in the roadmap is the lock.
         *
         *     The failure is one 401 with one message. "No such user" and "wrong password"
         *     are the same answer here, because telling them apart confirms which usernames
         *     exist.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie.
         *
         *     Unauthenticated on purpose: logging out with an already-expired session must
         *     work, and it is the one action whose whole effect is to remove authority.
         *
         *     The token itself is not revoked — nothing here keeps a denylist, so a token
         *     already copied off the machine stays valid until it expires. That is the
         *     honest cost of stateless sessions and the reason `api_session_hours` is
         *     hours rather than weeks.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the caller is, or 401.
         *
         *     The dashboard's first call on load: a 200 renders the app, a 401 renders the
         *     login screen. That keeps "am I logged in" a question the server answers,
         *     rather than something the client infers from a cookie it cannot read —
         *     `HttpOnly` means the page genuinely cannot see it.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_v1_backtests_get"];
        put?: never;
        /**
         * Run Backtest
         * @description Queue a run. Returns immediately with status `queued`.
         *
         *     Validate data coverage BEFORE queueing — telling the user up front that
         *     history is missing beats a job that fails four minutes in.
         */
        post: operations["run_backtest_api_v1_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Backtests
         * @description Metrics side by side.
         *
         *     Beware: comparing many variants and picking the best is how overfitting
         *     happens. The winner of a 200-way parameter sweep is usually the luckiest
         *     parameter set, not the best one. See docs/BACKTESTING.md.
         */
        post: operations["compare_backtests_api_v1_backtests_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_api_v1_backtests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}/equity-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Equity Curve */
        get: operations["get_backtest_equity_curve_api_v1_backtests__run_id__equity_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest Trades
         * @description Every simulated trade. Inspecting individual trades is how you catch a
         *     backtest that is "profitable" because of one impossible fill.
         */
        get: operations["get_backtest_trades_api_v1_backtests__run_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/equity-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Equity Curve
         * @description Equity over time, for the dashboard's headline chart.
         *
         *     Thinned to one point per bucket, keeping the **last** observation in each:
         *     equity is a level, and averaging the minute points inside an hour produces a
         *     number the account never actually held (`atp_core.dashboard.curve`).
         *
         *     `resolution` defaults to whatever keeps the requested window under a few
         *     hundred points, so a caller that has not thought about it gets a readable
         *     chart instead of a minute-resolution year.
         */
        get: operations["get_equity_curve_api_v1_dashboard_equity_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Health
         * @description Operational status: feed connected, broker reachable, worker heartbeat,
         *     DB lag, last reconciliation result.
         *
         *     Deliberately still unbuilt, and the blocker is worth naming: **there is no
         *     worker heartbeat**. The ingestor's `IngestorStats` and the reconciler's last
         *     report live in the worker's memory and are published nowhere, so the only
         *     thing this endpoint could honestly answer today is what `/dashboard/live`
         *     already carries — `last_data_at`, `data_feed_healthy` and the halt list.
         *     Building it means giving the worker a health key to write, which is a
         *     producer-side change and belongs with the Phase 6 metrics item rather than
         *     being faked here from what the API happens to be able to reach.
         */
        get: operations["get_system_health_api_v1_dashboard_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Live Dashboard
         * @description Everything the dashboard needs, from one point in time.
         *
         *     Fast by construction: it is polled by every open browser tab, so the book is
         *     one Redis `GET` of a document the worker already assembled rather than a
         *     recomputation from fills. The two other reads — the halt keys and, only when
         *     a book exists, one bounded equity query for the day anchor — are both small
         *     and both bounded.
         *
         *     Signals come back newest first, because a feed is read from the top.
         */
        get: operations["get_live_dashboard_api_v1_dashboard_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/bars/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bars
         * @description Historical bars for charting. Served from our own store, not the vendor —
         *     charts must not consume the broker's rate limit.
         */
        get: operations["get_bars_api_v1_market_data_bars__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Calendar
         * @description Sessions, holidays and early closes.
         *
         *     Inclusive of both ends: the arguments are calendar days rather than
         *     instants, and a range that quietly dropped its last day would be a trap.
         *
         *     Read straight from the exchange rules — no database, no vendor call — so
         *     this is safe to hit from a chart that needs to grey out non-trading days.
         */
        get: operations["get_market_calendar_api_v1_market_data_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/quote/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quote
         * @description Latest cached quote. Include `age_seconds` in the response so the client
         *     can grey out a stale price rather than displaying it as current.
         */
        get: operations["get_quote_api_v1_market_data_quote__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-data/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Symbols */
        get: operations["search_symbols_api_v1_market_data_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_v1_orders_get"];
        put?: never;
        /**
         * Submit Manual Order
         * @description Human-initiated order.
         *
         *     Goes through the SAME `OrderRouter` and risk engine as a strategy order
         *     (rule §1.5) — a manual order is not a reason to skip the limits, it is the
         *     single most common reason to need them. Audit-logged with `actor`.
         */
        post: operations["submit_manual_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/cancel-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel All Orders */
        post: operations["cancel_all_orders_api_v1_orders_cancel_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel Order */
        delete: operations["cancel_order_api_v1_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions */
        get: operations["list_positions_api_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position */
        get: operations["get_position_api_v1_positions__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{symbol}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Position
         * @description Flatten one position at market. Audit-logged.
         */
        post: operations["close_position_api_v1_positions__symbol__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/positions/{symbol}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Stop
         * @description Adjust a protective stop.
         *
         *     Widening a stop (moving it away from price) requires an explicit override
         *     flag and is audit-logged prominently. It is the most common way a
         *     disciplined system becomes an undisciplined one, usually at the exact moment
         *     discipline was needed.
         */
        patch: operations["update_stop_api_v1_positions__symbol__stop_patch"];
        trace?: never;
    };
    "/api/v1/risk/flatten-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flatten All
         * @description Liquidate everything at market.
         *
         *     Requires `confirm` to equal the literal string "FLATTEN ALL POSITIONS".
         *     Irreversible: it realises every open P&L at whatever the market offers.
         */
        post: operations["flatten_all_api_v1_risk_flatten_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/halt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Engage Kill Switch
         * @description STOP TRADING. Takes effect immediately for all processes.
         *
         *     No confirmation step by design — hesitation is the expensive part. Clearing
         *     it is the deliberate action (see below).
         */
        post: operations["engage_kill_switch_api_v1_risk_halt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Limits */
        get: operations["get_risk_limits_api_v1_risk_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/rejections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rejections
         * @description Recently blocked orders and why.
         *
         *     A strategy silently doing nothing because a limit rejects it every time
         *     looks identical to a strategy with no signals — this endpoint is how you
         *     tell the difference.
         */
        get: operations["list_rejections_api_v1_risk_rejections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Kill Switch
         * @description Resume trading. Requires a named human and is audit-logged.
         *
         *     Deliberately asymmetric with `/halt`: stopping is reflexive, restarting is
         *     a decision.
         */
        post: operations["clear_kill_switch_api_v1_risk_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk Status
         * @description Current usage against every limit: exposure, daily P&L, order rate,
         *     open position count. What a human checks before promoting to live.
         */
        get: operations["get_risk_status_api_v1_risk_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_v1_strategies_get"];
        put?: never;
        /**
         * Create Strategy
         * @description Validate before storing.
         *
         *     A `ruleset` is parsed through `RuleSet` here so a malformed rule fails at
         *     creation with a clear message, not at 09:31 next Tuesday inside the worker.
         */
        post: operations["create_strategy_api_v1_strategies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Strategy Classes
         * @description Registered strategy classes with their params JSON Schema — the frontend
         *     renders its configuration form from this.
         */
        get: operations["list_available_strategy_classes_api_v1_strategies_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_v1_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Strategy
         * @description Editing a strategy that is live requires pausing it first — swapping
         *     parameters underneath open positions leaves them orphaned from the logic
         *     that opened them.
         */
        patch: operations["update_strategy_api_v1_strategies__strategy_id__patch"];
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Strategy
         * @description Stop generating signals. Existing positions keep their stops unless
         *     `close_positions` — pausing must not silently strip protection.
         */
        post: operations["pause_strategy_api_v1_strategies__strategy_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{strategy_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote Strategy
         * @description Advance a stage.
         *
         *     Promotion to `live` additionally requires: a completed backtest on record,
         *     a minimum paper-trading period, `ATP_ALLOW_LIVE_TRADING=true`, and an audit
         *     entry naming a human. See docs/SAFETY.md.
         */
        post: operations["promote_strategy_api_v1_strategies__strategy_id__promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: is the process up? Must not touch the DB — a slow database
         *     should not cause the orchestrator to kill a healthy API.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: DB, Redis and broker reachable. Fail this to be removed from
         *     the load balancer without being restarted.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountView
         * @description Account-level figures, all from one book at one instant.
         *
         *     No `buying_power`: that is the venue's number and reading it costs a broker
         *     call per dashboard poll, on the same rate limit the trading process is
         *     placing orders against. `BuyingPowerRule` constrains against `cash`, so cash
         *     is the number that actually decides whether an order is approved here.
         */
        AccountView: {
            /** Cash */
            cash: string;
            /** Day Pnl */
            day_pnl: string | null;
            /** Day Pnl Pct */
            day_pnl_pct: string | null;
            /** Equity */
            equity: string;
            /** Gross Exposure */
            gross_exposure: string;
            /** Leverage */
            leverage: string | null;
            /** Net Exposure */
            net_exposure: string;
            /** Open Position Count */
            open_position_count: number;
            /** Realized Pnl */
            realized_pnl: string;
            /** Unmarked Symbols */
            unmarked_symbols?: string[];
            /** Unrealized Pnl */
            unrealized_pnl: string;
        };
        /** BacktestOut */
        BacktestOut: {
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            } | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Strategy Id */
            strategy_id: string;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Cost Model
             * @default alpaca_equities
             */
            cost_model: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * Starting Cash
             * @default 100000
             */
            starting_cash: number | string;
            /** Strategy Id */
            strategy_id: string;
            /** Symbols */
            symbols: string[];
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
        };
        /**
         * EquityCurveView
         * @description The account's equity over time, thinned to one point per bucket.
         */
        EquityCurveView: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Points */
            points?: components["schemas"]["EquityPointView"][];
            /** Resolution */
            resolution: string;
            /** Run Mode */
            run_mode: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** EquityPointView */
        EquityPointView: {
            /** Cash */
            cash: string;
            /** Equity */
            equity: string;
            /** Gross Exposure */
            gross_exposure: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HaltRequest */
        HaltRequest: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Reason
             * @default manual
             */
            reason: string;
            /**
             * Scope
             * @default global
             */
            scope: string;
            /** Target */
            target?: string | null;
        };
        /** HaltView */
        HaltView: {
            /** Detail */
            detail: string;
            /**
             * Engaged At
             * Format: date-time
             */
            engaged_at: string;
            /** Engaged By */
            engaged_by: string;
            /** Reason */
            reason: string;
            /** Scope */
            scope: string;
            /** Target */
            target: string | null;
        };
        /**
         * LiveDashboard
         * @description One screen, assembled from two sources — see the module docstring.
         */
        LiveDashboard: {
            account: components["schemas"]["AccountView"] | null;
            /** Active Halts */
            active_halts?: components["schemas"]["HaltView"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Book Age Seconds */
            book_age_seconds: number | null;
            /** Book As Of */
            book_as_of: string | null;
            /** Data Feed Healthy */
            data_feed_healthy: boolean | null;
            /** Last Data At */
            last_data_at: string | null;
            /** Market Open */
            market_open: boolean;
            /** Positions */
            positions?: components["schemas"]["PositionView"][];
            /** Recent Signals */
            recent_signals?: components["schemas"]["SignalView"][];
            /** Refresh Seconds */
            refresh_seconds: number;
            /** Run Mode */
            run_mode: string;
            /** Strategy */
            strategy: string | null;
            /** Symbols */
            symbols?: string[];
            /** Working Orders */
            working_orders?: components["schemas"]["OrderView"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** ManualOrderRequest */
        ManualOrderRequest: {
            /** Limit Price */
            limit_price?: number | string | null;
            /**
             * Order Type
             * @default market
             */
            order_type: string;
            /** Qty */
            qty: number | string;
            /** Reason */
            reason: string;
            /** Side */
            side: string;
            /** Stop Loss Price */
            stop_loss_price?: number | string | null;
            /** Symbol */
            symbol: string;
        };
        /**
         * MarketCalendarView
         * @description Sessions, holidays and early closes over a range.
         */
        MarketCalendarView: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** Exchange */
            exchange: string;
            /** Holidays */
            holidays?: string[];
            /** Sessions */
            sessions: components["schemas"]["SessionView"][];
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Timezone */
            timezone: string;
        };
        /** OrderView */
        OrderView: {
            /** Avg Fill Price */
            avg_fill_price: string | null;
            /** Client Order Id */
            client_order_id: string;
            /** Filled Qty */
            filled_qty: string;
            /** Id */
            id: string;
            /** Limit Price */
            limit_price: string | null;
            /** Order Type */
            order_type: string;
            /** Qty */
            qty: string;
            /** Side */
            side: string;
            /** Status */
            status: string;
            /** Stop Price */
            stop_price: string | null;
            /** Strategy Id */
            strategy_id: string | null;
            /** Symbol */
            symbol: string;
            /** Ts */
            ts: string | null;
        };
        /**
         * PositionView
         * @description One holding.
         *
         *     Every mark-dependent figure is nullable, and that is not defensive typing:
         *     an unmarked position is not a position worth nothing. `market_value`
         *     reported as 0 would put a real holding at the bottom of the exposure column
         *     and make a breached limit look compliant. `unmarked_symbols` on the account
         *     says which ones, so the reader is told rather than left to notice.
         */
        PositionView: {
            /** Avg Entry Price */
            avg_entry_price: string;
            /** Distance To Stop Pct */
            distance_to_stop_pct: string | null;
            /** Fees Paid */
            fees_paid: string;
            /** Last Price */
            last_price: string | null;
            /** Market Value */
            market_value: string | null;
            /** Opened At */
            opened_at: string | null;
            /** Qty */
            qty: string;
            /** Realized Pnl */
            realized_pnl: string;
            /** Stop Loss Price */
            stop_loss_price: string | null;
            /** Symbol */
            symbol: string;
            /** Take Profit Price */
            take_profit_price: string | null;
            /** Unrealized Pnl */
            unrealized_pnl: string | null;
            /** Unrealized Pnl Pct */
            unrealized_pnl_pct: string | null;
        };
        /**
         * PreSessionContext
         * @description What the login screen is allowed to know before anyone has signed in.
         */
        PreSessionContext: {
            /** Run Mode */
            run_mode: string;
        };
        /**
         * SessionView
         * @description One trading session.
         *
         *     `day` is the exchange-local date — the only stable name for a session, since
         *     the same one opens at 14:30Z in winter and 13:30Z in summer. The bounds are
         *     UTC (rule §1.2); a client that wants New York wall-clock converts using
         *     `MarketCalendarView.timezone`.
         */
        SessionView: {
            /**
             * Close At
             * Format: date-time
             */
            close_at: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Is Early Close */
            is_early_close: boolean;
            /**
             * Open At
             * Format: date-time
             */
            open_at: string;
        };
        /**
         * SignalView
         * @description A recent decision, with its reasoning — requirement #7's "trades selected
         *     based on preset rules".
         *
         *     `indicators` values are strings, not numbers. An indicator value is usually
         *     a price — an SMA of closes is denominated in dollars — and rule §1.1's
         *     exemption for indicator maths covers computing one, not putting it on a wire
         *     whose only numeric type is a binary float.
         */
        SignalView: {
            /** Acted On */
            acted_on: boolean;
            /** Action */
            action: string;
            /** Id */
            id: string;
            /** Indicators */
            indicators?: {
                [key: string]: string;
            };
            /** Reason */
            reason: string;
            /** Rejected By */
            rejected_by: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
            /** Strategy Id */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** StrategyCreate */
        StrategyCreate: {
            /** Class Name */
            class_name?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Risk Config
             * @default {}
             */
            risk_config: {
                [key: string]: unknown;
            };
            /** Ruleset */
            ruleset?: {
                [key: string]: unknown;
            } | null;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /** Universe */
            universe: string[];
        };
        /** StrategyOut */
        StrategyOut: {
            /** Class Name */
            class_name?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Risk Config
             * @default {}
             */
            risk_config: {
                [key: string]: unknown;
            };
            /** Ruleset */
            ruleset?: {
                [key: string]: unknown;
            } | null;
            /** State */
            state: string;
            /**
             * Timeframe
             * @default 1d
             */
            timeframe: string;
            /** Universe */
            universe: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhoAmI */
        WhoAmI: {
            /** User */
            user: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_attribution_api_v1_analytics_attribution_get: {
        parameters: {
            query?: {
                by?: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_vs_backtest_api_v1_analytics_live_vs_backtest__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_performance_api_v1_analytics_performance_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                strategy_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_report_api_v1_analytics_reports_daily_get: {
        parameters: {
            query?: {
                day?: string | null;
                output_format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_api_v1_analytics_trades_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                strategy_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    context_api_v1_auth_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreSessionContext"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
        };
    };
    list_backtests_api_v1_backtests_get: {
        parameters: {
            query?: {
                strategy_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_backtest_api_v1_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_backtests_api_v1_backtests_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_api_v1_backtests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_equity_curve_api_v1_backtests__run_id__equity_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_trades_api_v1_backtests__run_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equity_curve_api_v1_dashboard_equity_curve_get: {
        parameters: {
            query?: {
                days?: number;
                /** @description one of 1m, 5m, 15m, 1h, 4h, 1d; omitted picks one to suit `days` */
                resolution?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityCurveView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_health_api_v1_dashboard_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_live_dashboard_api_v1_dashboard_live_get: {
        parameters: {
            query?: {
                /** @description most recent decisions to return */
                signal_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bars_api_v1_market_data_bars__symbol__get: {
        parameters: {
            query?: {
                timeframe?: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_calendar_api_v1_market_data_calendar_get: {
        parameters: {
            query?: {
                /** @description first day, inclusive */
                start?: string | null;
                /** @description last day, inclusive */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketCalendarView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_v1_market_data_quote__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_symbols_api_v1_market_data_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_v1_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                symbol?: string | null;
                strategy_id?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_manual_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_all_orders_api_v1_orders_cancel_all_post: {
        parameters: {
            query?: {
                symbol?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_api_v1_positions_get: {
        parameters: {
            query?: {
                open_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_api_v1_positions__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_position_api_v1_positions__symbol__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_api_v1_positions__symbol__stop_patch: {
        parameters: {
            query: {
                stop_loss_price: number | string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flatten_all_api_v1_risk_flatten_all_post: {
        parameters: {
            query: {
                confirm: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    engage_kill_switch_api_v1_risk_halt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HaltRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_limits_api_v1_risk_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_rejections_api_v1_risk_rejections_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_kill_switch_api_v1_risk_resume_post: {
        parameters: {
            query: {
                scope: string;
                target?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_status_api_v1_risk_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_strategy_api_v1_strategies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_strategy_classes_api_v1_strategies_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_strategy_api_v1_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_api_v1_strategies__strategy_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_strategy_api_v1_strategies__strategy_id__pause_post: {
        parameters: {
            query?: {
                close_positions?: boolean;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_strategy_api_v1_strategies__strategy_id__promote_post: {
        parameters: {
            query: {
                target_state: string;
                confirmed_by: string;
            };
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
